# docker-compose.yml
services:
  omnihr:
    build:
      context: .
      dockerfile: Dockerfile
    image: truongthuanr/omnihr:latest
    container_name: omnihr-service
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./configs/customconfig.json:/configs/config.json
    environment:
      CONFIG_PATH: /configs/config.json
      DB_HOST: omnihrdb
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: omnihrdb
    networks:
      - omnihr-net

networks:
  omnihr-net:
    external: true
