INSERT INTO statuses (id, name) VALUES
(1, 'active'),
(2, 'not_started'),
(3, 'terminated');

INSERT INTO departments (name) VALUES
    ('Engineering'),
    ('Marketing'),
    ('Sales'),
    ('Customer Support'),
    ('Human Resources'),
    ('Finance'),
    ('Legal'),
    ('IT'),
    ('Operations'),
    ('Product'),
    ('Design'),
    ('Quality Assurance'),
    ('Business Development'),
    ('Logistics'),
    ('Procurement');

INSERT INTO positions (name) VALUES
    ('Software Engineer'),
    ('Backend Developer'),
    ('Frontend Developer'),
    ('DevOps Engineer'),
    ('QA Engineer'),
    ('UX/UI Designer'),
    ('Product Manager'),
    ('Project Manager'),
    ('Business Analyst'),
    ('Data Analyst'),
    ('HR Specialist'),
    ('Recruiter'),
    ('Marketing Manager'),
    ('Content Strategist'),
    ('Sales Executive'),
    ('Account Manager'),
    ('Customer Service Rep'),
    ('Operations Manager'),
    ('Legal Counsel'),
    ('Finance Analyst');

INSERT INTO organizations (id, name) VALUES
    (1, 'OMNI HR'),
    (2, 'Workday Inc.'),
    (3, 'BambooHR'),
    (4, 'SAP SuccessFactors'),
    (5, 'ADP Workforce');

INSERT INTO org_api_keys (api_key, organization_id, description) VALUES
    ('key-omnihr-001', 1, 'API key for OMNI HR'),
    ('key-workday-001', 2, 'API key for Workday Inc.'),
    ('key-bamboohr-001', 3, 'API key for BambooHR'),
    ('key-sap-001', 4, 'API key for SAP SuccessFactors'),
    ('key-adp-001', 5, 'API key for ADP Workforce');

INSERT INTO locations (name) VALUES
    ('United States'),
    ('Canada'),
    ('United Kingdom'),
    ('Germany'),
    ('France'),
    ('Italy'),
    ('Spain'),
    ('Netherlands'),
    ('Sweden'),
    ('Norway'),
    ('Denmark'),
    ('Finland'),
    ('Poland'),
    ('Austria'),
    ('Switzerland'),
    ('Australia'),
    ('New Zealand'),
    ('Japan'),
    ('South Korea'),
    ('China'),
    ('India'),
    ('Brazil'),
    ('Mexico'),
    ('Argentina'),
    ('Chile'),
    ('Colombia'),
    ('South Africa'),
    ('Egypt'),
    ('Nigeria'),
    ('Kenya'),
    ('Russia'),
    ('Ukraine'),
    ('Czech Republic'),
    ('Hungary'),
    ('Romania'),
    ('Turkey'),
    ('Thailand'),
    ('Vietnam'),
    ('Indonesia'),
    ('Malaysia'),
    ('Philippines'),
    ('Singapore'),
    ('Pakistan'),
    ('Bangladesh'),
    ('Greece'),
    ('Portugal'),
    ('Ireland'),
    ('Israel'),
    ('UAE'),
    ('Saudi Arabia');

INSERT INTO companies (name) VALUES
    ('Globex Corporation'),
    ('Initech'),
    ('Umbrella Corp'),
    ('Stark Industries'),
    ('Wayne Enterprises'),
    ('Acme Corp'),
    ('Hooli'),
    ('Wonka Industries'),
    ('Cyberdyne Systems'),
    ('Pied Piper'),
    ('Dunder Mifflin'),
    ('Massive Dynamic'),
    ('Gekko & Co'),
    ('Prestige Worldwide'),
    ('Oscorp'),
    ('Tyrell Corporation'),
    ('Vehement Capital Partners'),
    ('BLUTH Company'),
    ('Octan Corp'),
    ('Virtucon'),
    ('Gringotts Bank'),
    ('Monarch Solutions'),
    ('Nakatomi Trading'),
    ('Vandelay Industries'),
    ('Soylent Corp'),
    ('Zorg Industries'),
    ('LexCorp'),
    ('Abstergo'),
    ('Black Mesa'),
    ('Illuminati Holdings'),
    ('Sirius Cybernetics Corp'),
    ('CyberLife'),
    ('Militech'),
    ('Korporation'),
    ('Hyperion'),
    ('Orbital Sciences'),
    ('Future Tech'),
    ('New Dawn Technologies'),
    ('Quantum Solutions'),
    ('Phoenix Group'),
    ('Zephyr Inc'),
    ('NextGen Labs'),
    ('Blue Sun Corp'),
    ('Infocom'),
    ('Parallax Systems'),
    ('NovaTech'),
    ('Omni Consumer Products'),
    ('Encom'),
    ('Paper Street Co'),
    ('Halcyon Dynamics'),
    ('Ascendant Systems'),
    ('Redwood Group'),
    ('Avalon Solutions'),
    ('TerraCorp'),
    ('CoreLogic'),
    ('Apollo AI'),
    ('DeepCore Mining'),
    ('Veridian Dynamics'),
    ('BabelTech'),
    ('SkyNet Analytics'),
    ('Genesis Labs'),
    ('Neptune Networks'),
    ('IronClad Security'),
    ('StratosCorp'),
    ('Atlas Systems'),
    ('Prime Movers'),
    ('ChronoTech'),
    ('Titan Ventures'),
    ('Arcadia Group'),
    ('Lucid Logic'),
    ('BrightWave'),
    ('Nimbus Systems'),
    ('Zion Technologies'),
    ('Helix Dynamics'),
    ('ForgeWorks'),
    ('NetSphere'),
    ('Echelon Corp'),
    ('Solstice Group'),
    ('Synapse AI'),
    ('Ignite Global'),
    ('MiraTech'),
    ('Synthetix'),
    ('Altura Labs'),
    ('CarbonWorks'),
    ('Equinox Group'),
    ('Catalyst One'),
    ('RedCore'),
    ('Vortex Dynamics'),
    ('NovaForge'),
    ('Zenith AI'),
    ('Optima Corp'),
    ('Polarix'),
    ('Infinium Group'),
    ('ZeroPoint Systems'),
    ('Lumina Systems'),
    ('Omnia Group'),
    ('Tesseract Solutions'),
    ('DeltaCorp');